lib/resque/pool/pooled_worker.rb

Fixes #116
This is fairly ugly, because of the `alias_method` of initialize... if you have any suggestions on how to fix it a different way, I can try something else.  Tested and works for me though, and most importantly, fixes the problem with using resque-pool in a docker env.

Bringing back master pid detection, to fix docker

---

CONTRIBUTING.md

I want to get the ball rolling on #109 so that pull requests and issues will be resolved and maintenance can resume.
@spajus and @nevans: any thoughts?

Quick and dirty CONTRIBUTING.md

---

.travis.yml

Would be great to know that Ruby 2.1.2 is supported.

Add Ruby 2.1.2 to Travis build matrix

---

lib/resque/pool.rb

This is a fix for #106.
It came from the necessity of having BugSnag notifications working correctly with Resque Pool.

Pass ENV['RUN_AT_EXIT_HOOKS'] to Resque worker

---

lib/resque/pool.rb
lib/resque/pool/cli.rb

- If TERM_CHILD is set, then default to graceful-wait behaviour,
which seems to be what Heroku expects.
- Allow override via --term-graceful or --term-graceful-wait, which
also both respect TERM_CHILD and pass TERM to workers when that's set.
- Log the signal we are sending to children, for extra peace of mind.
- Log a warning if it looks like we are running on Heroku and TERM_CHILD
is not set.
Fixes #98 and #97

Better TERM_CHILD default handling for Heroku

---

lib/resque/pool.rb
lib/resque/pool/cli.rb

We're running a dozen of servers with resque-pool managing resque workers, and there is one issue that happens from time to time causing us trouble. This pull request addresses it.
When resque workers break on startup (i.e. bad code was deployed), resque-pool goes into a loop that keeps respawning dead workers, putting the server under very heavy load. `spawn_delay` option would add a delay before respawning every missing worker and should keep CPU from redlining when resque workers fail to start.

Add option to spawn missing workers with delay

---

lib/resque/pool.rb
spec/resque_pool_spec.rb

This allows the hook to respond based on e.g. which queues the worker is
running.

Pass worker instance to after_prefork hook

---

lib/resque/pool/logging.rb
spec/logging_spec.rb

As per Issue #30 I've ported Unicorn's code for reopening log files to resque-pool.
A few notes:
1. I haven't yet tested this in production myself.  I plan on getting it in today or this weekend.
2. I ported over all of Unicorn's tests for re-opening log files to RSpec.  The last one that tests encodings takes a while to run.
3. I added a few more additional checks to make sure that the reopening mechanism is working as expected.
On my development machine, things appear to be working as expected when I send a HUP to the resque-pool master.

Reopening log files now reopens all logs in memory

---

lib/resque/pool/cli.rb
resque-pool.gemspec

1 less dependency and gives a little bit more fine-grained control :)
@nevans 
before:
```
./bin/resque-pool -h
resque-pool is the best way to manage a group (pool) of resque workers
When daemonized, stdout and stderr default to resque-pool.stdxxx.log files in
the log directory and pidfile defaults to resque-pool.pid in the current dir.
Usage:
resque-pool [options]
where [options] are:
-c, --config=<s>              Alternate path to config file
-a, --appname=<s>             Alternate appname
-d, --daemon                  Run as a background daemon
-o, --stdout=<s>              Redirect stdout to logfile
-e, --stderr=<s>              Redirect stderr to logfile
-n, --nosync                  Don't sync logfiles on every write
-p, --pidfile=<s>             PID file location
-E, …
```

kick out trollop

---

README.md
examples/upstart-reload.conf
examples/upstart.conf
lib/resque/pool/cli.rb
spec/cli_spec.rb

This PR includes the remaining differences in [ShippingEasy's resque-pool fork](https://github.com/ShippingEasy/resque-pool), both of which are optional command line flags that tweak startup behavior to support zero-downtime deployment strategies and running resque-pool inside a process supervisor.
The normal approach to deploying new worker code is to signal resque-pool to gracefully shutdown with `QUIT` or `INT`, then start up a new instance.  The problem with that approach is that long-running jobs and slow app startup can lead to a dramatic reduction in worker throughput during a deploy, which in our case is unacceptable.
The technique we use to maintain full throughput during deploys is to start a second resque-pool instance with the new code which loads a rails environment and …

Options to aid zero-downtime deployment / process supervision

---

Rakefile
resque-pool.gemspec
spec/logging_spec.rb

`rake spec` had become unbearably slow, with one of the specs that loops over all combinations of input/output encodings. I think we can safely get by with only running that spec during the continuous integration build. I tagged it as `slow` and made the `rake spec` task ignore `slow` specs.
`rake spec:ci` will run all specs. This is what will run in the Travis CI build.
Also updated the rspec version to match the version already used in Travis CI build. This ensures a more consistent experience between dev and CI, and allows using some of the newer rspec features.

Make `rake spec` fast again

---

lib/resque/pool.rb
lib/resque/pool/cli.rb
lib/resque/pool/killer.rb
lib/resque/pool/logging.rb
spec/killer_spec.rb

Adds the `--kill-others` command line option.
When this option is set, resque-pool will send a graceful
shutdown signal to all other running resque-pools.
This is useful in "no downtime deploy" scenarios,
where you want the pool running the new code to
completely load its environment and be ready to
process work *before* shutting down the old code.
Once the new code is ready, it will shut down the
old processes for you.
See also https://github.com/nevans/resque-pool/pull/132

Option to kill other resque-pool instances on startup

---

lib/resque/pool/file_or_hash_loader.rb
spec/resque_pool_spec.rb

Avoid polluting the consumer's global namespace.

Move FileOrHashLoader into Resque::Pool namespace

---

lib/resque/pool/killer.rb

`Open3.capture3` is vulnerable to deadlock because it has two threads
doing blocking reads on separate stderr/stdout pipes, each with limited
buffer size.
In this case, we only need stdout to parse the pids. We want stderr in
case the ps command fails. So we get the best of both worlds by
redirecting stderr to stdout, relying on exitstatus to decide whether
the command succeeded, and showing full output if it didn't.

Fix occasional all_resque_pool_processes deadlock

---

lib/resque/pool/cli.rb

If `pidfile` points to an empty file, or contains non-numeric data`old_pid` will be 0. It's also possible for pidfile to contain '-1'. In both cases `Process.kill` returns 1 on my system, so resque-pool will erroneously think the old process is still running.

catch edge cases where old_pid is invalid

---

lib/resque/pool.rb
spec/resque_pool_spec.rb

This would otherwise create an error in resque[1] where this value is
multiplied by 10 and would result in the value in the ENV hash
duplicated 10 times as a String.
[1]: https://github.com/resque/resque/blob/cde288ac45cee0e9b52bf27bde57670a1d240fe8/lib/resque/worker.rb#L550

Resque::Pool: Cast term timeout from env to float

---

resque-pool.gemspec

Just changed gemspec to allow resque 2.x. 
Tests still pass for me locally with `bundle exec rspec` -- is that enough to be confident resque 2.0 is no problem?
Ref: #170

allow resque 2.0

---

README.md
lib/resque/pool/config_throttle.rb
spec/config_throttle_spec.rb

Many custom configuration loaders will retrieve the
configuration from an external resource. `Resque::Pool`
asks the loader for the latest configuration roughly
once per second. You may want to reduce load on your
external resource by caching the value, and only
really fetching the latest configuration after a
specific amount of time has passed.
Instead of forcing each configuration loader author
to re-write (and test) this logic, we provide `Resque::Pool::ConfigThrottle`.
See the spec for full details of its behavior.

Throttle calls to a custom configuration loader

---

lib/resque/pool.rb

Can be used to hook into pool manager (e.g. to report on workers).
<hr>
Sorry for not opening an issue beforehand, maybe we can discuss the utility of this addition here as well.
The main idea behind this addition, is to allow the user of a pool to write some code that runs within the pool manager by request of a signal.
Due to the lack of available signal codes, I have chosen the relatively well fitting Signal 29 SIGINFO also known as SIGPOLL or SIGIO.
In our case, we needed a facility to regularly report the current process pids on long running jobs.
On one side we would store the worker hostname + worker pid when starting the job.
On the other side, we would regularly query the pool manager (with a signal) to report on its running processes.
That way, we are always able to compare the …

Introduce siginfo-hook and SIGINFO 29 signal handling

---

.github/workflows/codeql-analysis.yml

This is simply the auto-generated yaml config, taken verbatim from GitHub's "Security overview" -> "Code scanning alerts" -> "Setup Code Scanning"

Adding code scanning action

---

resque-pool.gemspec

* **📚 Fix Changelog URI in gemspec metadata**
This was previously pointing to the `resque` repo's History.md file!
* **📧 Update my email in the gemspec**
This is the email I have configured for my rubygems.org account.
* **📚 Update gemspec URIs with transferred repo owner**
This repo was transferred from my github user (`nevans`) to the `resque` organization.
* **🔒 Explicitly require MFA to publish gem**
I believe this was probably already _implicitly_ required, but putting it in the gemspec metadata helps tooling (which might audit for this) and will be reflected on the rubygems.org web site.
* **⬆️ Relax rake gem dependency constraint**
It is _very_ unlikely that rake will be updated in an incompatible way.

Update gemspec metadata
